## Word Frequency Distribution

In [10]:
from collections import Counter
import nltk
from nltk.tokenize import word_tokenize
nltk.download('punkt_tab')

def word_frequency(text):
    words = word_tokenize(text.lower())
    return Counter(words)

text = "NLP is amazing. NLP makes machines understand text."
print("Word Frequencies:", word_frequency(text))

Word Frequencies: Counter({'nlp': 2, '.': 2, 'is': 1, 'amazing': 1, 'makes': 1, 'machines': 1, 'understand': 1, 'text': 1})


[nltk_data] Downloading package punkt_tab to C:\Users\Jagdish
[nltk_data]     singh\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


In [11]:
def word_frequency(text):
    words = text.lower().split()
    return Counter(words)

text = "NLP is amazing. NLP makes machines understand text."
print("Word Frequencies:", word_frequency(text))

Word Frequencies: Counter({'nlp': 2, 'is': 1, 'amazing.': 1, 'makes': 1, 'machines': 1, 'understand': 1, 'text.': 1})


## BOW

In [12]:
from sklearn.feature_extraction.text import CountVectorizer

corpus = [
    "NLP is fun and exciting",
    "Machines understand NLP and text",
    "Text processing is part of NLP"
]

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)

print("Feature Names:", vectorizer.get_feature_names_out())
print("BoW Representation:")
print(X.toarray())

Feature Names: ['and' 'exciting' 'fun' 'is' 'machines' 'nlp' 'of' 'part' 'processing'
 'text' 'understand']
BoW Representation:
[[1 1 1 1 0 1 0 0 0 0 0]
 [1 0 0 0 1 1 0 0 0 1 1]
 [0 0 0 1 0 1 1 1 1 1 0]]


## TF-IDF

In [13]:

corpus = [
    "NLP is fun and exciting",
    "Machines understand NLP and text",
    "Text processing is part of NLP"
]

In [14]:
# Top Keywords: ['processing' 'of' 'part' 'is' 'text']

In [15]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(corpus)

print("Feature Names:", vectorizer.get_feature_names_out())
print("TF-IDF Representation:")
print(X.toarray())

Feature Names: ['and' 'exciting' 'fun' 'is' 'machines' 'nlp' 'of' 'part' 'processing'
 'text' 'understand']
TF-IDF Representation:
[[0.40619178 0.53409337 0.53409337 0.40619178 0.         0.31544415
  0.         0.         0.         0.         0.        ]
 [0.40619178 0.         0.         0.         0.53409337 0.31544415
  0.         0.         0.         0.40619178 0.53409337]
 [0.         0.         0.         0.35829137 0.         0.27824521
  0.4711101  0.4711101  0.4711101  0.35829137 0.        ]]


Using Numpy


In [16]:
import numpy as np

corpus = [
    "NLP is fun and exciting",
    "Machines understand NLP and text",
    "Text processing is part of NLP"
]

tokenized = [[w for w in doc.lower().split() if w.isalnum() and len(w) >= 2] for doc in corpus]
vocab = sorted(list(set(w for doc in tokenized for w in doc)))

N = len(corpus)
V = len(vocab)
print("Feature Names:", np.array(vocab))

tf = np.zeros((N, V))
for i, doc in enumerate(tokenized):
    for w in doc:
        if w in vocab:
            tf[i, vocab.index(w)] += 1

df = np.sum(tf > 0, axis=0)
idf = np.log((1 + N) / (1 + df)) + 1

tfidf = tf * idf

norms = np.linalg.norm(tfidf, axis=1, keepdims=True)
norms[norms == 0] = 1
tfidf_norm = tfidf / norms

print("\nTF-IDF Representation:")
print(np.round(tfidf_norm, 4))

Feature Names: ['and' 'exciting' 'fun' 'is' 'machines' 'nlp' 'of' 'part' 'processing'
 'text' 'understand']

TF-IDF Representation:
[[0.4062 0.5341 0.5341 0.4062 0.     0.3154 0.     0.     0.     0.
  0.    ]
 [0.4062 0.     0.     0.     0.5341 0.3154 0.     0.     0.     0.4062
  0.5341]
 [0.     0.     0.     0.3583 0.     0.2782 0.4711 0.4711 0.4711 0.3583
  0.    ]]


## NLP Task - Keyword Extraction

In [17]:

corpus = [
    "NLP is fun and exciting",
    "Machines understand NLP and text",
    "Text processing is part of NLP"
]

In [18]:
import numpy as np

feature_array = np.array(vectorizer.get_feature_names_out())
importance = np.argsort(X.toarray()).flatten()[::-1]

keywords = feature_array[importance[:5]]
print("Top Keywords:", keywords)
print(feature_array)

Top Keywords: ['processing' 'of' 'part' 'is' 'text']
['and' 'exciting' 'fun' 'is' 'machines' 'nlp' 'of' 'part' 'processing'
 'text' 'understand']


this is correct method above one is wrong to calculate highest priority 

In [19]:
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer

corpus = [
    "NLP is fun and exciting",
    "Machines understand NLP and text",
    "Text processing is part of NLP"
]
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(corpus)
feature_array = np.array(vectorizer.get_feature_names_out())

global_weights = np.sum(X.toarray(), axis=0)

importance = np.argsort(global_weights)[::-1]

keywords = feature_array[importance[:5]]

print("Top Global Keywords:", keywords)

Top Global Keywords: ['nlp' 'and' 'text' 'is' 'understand']
